"""Identity and burst-dedup helpers shared by report consumers.

New reports carry a daily HMAC reporter bucket generated by the Worker. It is
stable just long enough to count independent sources for a promotion decision,
but cannot be reversed to an IP or linked across days. Legacy reports do not
have that field, so the short burst window remains as a conservative backstop.

Both consumers of `data/reports/` therefore need a backstop:

* `generate_hot_list.py` — duplicates read as velocity and promote the number
  onto the hot list, which every device syncs every 30 minutes into a
  high-priority checker.
* `merge_community_reports.py` — duplicates inflate the shipped `reports` count,
  and a burst of `not_spam` votes can de-list a genuine community row one vote
  at a time.

The burst window is deliberately much tighter than the Worker's 300 seconds:
within a minute a legacy repeat is more likely one person double-tapping, while
reports further apart are retained for the durable database (but never count as
independent evidence for a hot-list/domain promotion).
"""

import re
from datetime import datetime, timezone

BURST_DUPLICATE_SECONDS = 60
REPORTER_BUCKET_RE = re.compile(r"^[a-f0-9]{16}$")
REPORT_ID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")


def validated_reporter_bucket(value: object) -> str:
    """Return a valid opaque reporter bucket, or an empty string."""
    if not isinstance(value, str):
        return ""
    normalized = value.strip().lower()
    return normalized if REPORTER_BUCKET_RE.fullmatch(normalized) else ""


# Mobile carriers hand each device its own /64 out of a shared /48, so one
# carrier's customers are separate reporters. A home line with a delegated /56
# or /48 could rotate /64s, so no /48 counts for more than this many.
MAX_DEVICES_PER_GROUP = 2


def reporter_identity(report: dict) -> tuple[str, str] | None:
    """Return a report's (group, device) buckets, or None without a valid group.

    `reporter_bucket` is the Worker's daily HMAC of the reporter's /48 (or IPv4
    address) and `reporter_device` the same for the /64. A report stored before
    the device bucket existed counts as a single device of its group, which is
    how it was counted then.
    """
    group = validated_reporter_bucket(report.get("reporter_bucket"))
    if not group:
        return None
    return group, validated_reporter_bucket(report.get("reporter_device")) or group


def capped_reporter_count(identities) -> int:
    """Count distinct devices, at most MAX_DEVICES_PER_GROUP from any one group."""
    devices_by_group: dict[str, set[str]] = {}
    for group, device in identities:
        devices_by_group.setdefault(group, set()).add(device)
    return sum(min(len(devices), MAX_DEVICES_PER_GROUP) for devices in devices_by_group.values())


def busiest_day_reporters(dated_identities, count=capped_reporter_count) -> int:
    """Reporters shown to be different people: the count on the busiest UTC day.

    The Worker derives every bucket from the UTC day, so one reporter's reports
    either side of midnight carry different buckets. Only identities seen on the
    same day are known to be different reporters. `dated_identities` holds
    `(day, identity)` pairs and `count` counts one day's identities.
    """
    by_day: dict[str, set] = {}
    for day, identity in dated_identities:
        by_day.setdefault(day, set()).add(identity)
    return max((count(identities) for identities in by_day.values()), default=0)


def validated_report_id(value: object) -> str:
    """Return the id the app gave a report, lowercased, or an empty string."""
    if not isinstance(value, str):
        return ""
    normalized = value.strip().lower()
    return normalized if REPORT_ID_RE.fullmatch(normalized) else ""


def find_resent_reports(entries) -> set:
    """Return the tokens of reports that carry an id an earlier report already had.

    The app gives every report an id and keeps it for every attempt, so two
    stored reports with one id are one report sent twice: its first response
    was lost, or the phone changed networks mid-send, which also changes its
    reporter bucket and would otherwise count it as a second reporter.

    `entries` is an iterable of `(report_id, timestamp, token)`. The earliest
    copy is kept, and a report without an id never matches another.
    """
    grouped: dict[str, list] = {}
    for report_id, timestamp, token in entries:
        if report_id:
            grouped.setdefault(report_id, []).append((timestamp, token))
    epoch = datetime.min.replace(tzinfo=timezone.utc)
    resent = set()
    for group in grouped.values():
        group.sort(key=lambda item: (item[0] is None, item[0] or epoch, str(item[1])))
        resent.update(token for _, token in group[1:])
    return resent


def reporter_day_key(bucket: str, reported_at: datetime | None) -> tuple[str, str] | None:
    """Return the bucket's daily dedup key when both fields are trustworthy."""
    if not bucket or reported_at is None:
        return None
    return bucket, reported_at.astimezone(timezone.utc).date().isoformat()


def parse_reported_at(value: object) -> datetime | None:
    """Parse a report's `reported_at`, or None when it is missing/unparseable."""
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    # Naive timestamps are treated as UTC so comparisons never raise.
    return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=timezone.utc)


def find_burst_duplicates(entries, window_seconds: int = BURST_DUPLICATE_SECONDS) -> set:
    """Return the tokens of entries that repeat an earlier one within the window.

    `entries` is an iterable of `(key, timestamp, token)`:
      key       - what counts as "the same report" (a number, or number+type)
      timestamp - a `datetime` or None; None is never treated as a duplicate,
                  because an unparseable timestamp is no evidence of a burst
      token     - the caller's handle for the entry (filename, index, ...)

    Tokens must be unique and hashable. The first report in a burst is kept; the
    ones following it inside the window are returned.
    """
    grouped: dict[object, list] = {}
    for key, timestamp, token in entries:
        grouped.setdefault(key, []).append((timestamp, token))

    duplicates = set()
    epoch = datetime.min.replace(tzinfo=timezone.utc)
    for group in grouped.values():
        # Unparseable timestamps sort last so they never suppress a real report.
        group.sort(key=lambda item: (item[0] is None, item[0] or epoch))
        last_counted: datetime | None = None
        for timestamp, token in group:
            if (
                timestamp is not None
                and last_counted is not None
                and (timestamp - last_counted).total_seconds() < window_seconds
            ):
                duplicates.add(token)
                continue
            if timestamp is not None:
                last_counted = timestamp
    return duplicates
